version: 2
jobs:
  build:

    working_directory: ~/repo

    docker:
    # See https://circleci.com/docs/2.0/circleci-images/ ...
    - image: circleci/openjdk:8-jdk-browsers

    steps:

    - checkout

    - run:
        # @cgrossde I dont understand why this is needed here but not in your builds, see https://stackoverflow.com/questions/49163104/how-to-resolve-term-not-set-on-gradlew-assemblerelease-on-circleci
        name: Configure Env Vars
        command: |
          echo 'export TERM=xterm' >> $BASH_ENV
          echo -e "export BRANCH_NAME=`echo $CIRCLE_BRANCH | sed 's/\//\-/' | sed 's/\#/\-/'`" >> $BASH_ENV
          echo 'export BUILD_NUMBER=$CIRCLE_BUILD_NUM' >> $BASH_ENV

    - run:
        name: Clean & install
        command: ./gradlew clean build -x test -i -s --no-daemon

    - run:
        name: Tests
        command: ./gradlew test -i -s --no-daemon

    - run:
        name: Publish Scenarioo E2E Test Docu Reports to http://demo.scenarioo.org
        command: |
          mkdir -p artifacts
          export SCENARIOO_INSTANCE_FOR_DEPLOY=$([ "$BRANCH_NAME" == "master" ] && echo "master" || echo "develop")
          echo "Publishing Scenarioo Test Documentation Reports to http://demo.scenarioo.org/scenarioo-${SCENARIOO_INSTANCE_FOR_DEPLOY} ..."
          pushd build/scenariooDocumentation
          zip -r ../e2eScenariooDocu.zip ./*
          popd
          echo "Uploading ... "
          curl -f --user scenarioo:$TOMCAT_USER_PASSWORD -F"file=@build/e2eScenariooDocu.zip" http://demo.scenarioo.org/scenarioo-${SCENARIOO_INSTANCE_FOR_DEPLOY}/rest/builds
          echo -e "Pizza Delivery Scenarioo E2E Test Docu Reports:\nhttp://demo.scenarioo.org/scenarioo-${SCENARIOO_INSTANCE_FOR_DEPLOY}/#/?branch=pizza-delivery-${BRANCH_NAME}&build=build-${BUILD_NUMBER}\n" >> ./artifacts/build-result-summary.txt
          echo "Pizza Delivery Scenarioo E2E Test Documentation Reports published to http://demo.scenarioo.org/scenarioo-${SCENARIOO_INSTANCE_FOR_DEPLOY}/#/?branch=pizza-delivery-${BRANCH_NAME}&build=build-${BUILD_NUMBER}"
        when: always

    - store_test_results:
        path: build/test-results

    - run:
        name: Collect artifacts
        command: |
          cp -pR build/test-results artifacts || true
          cp -pR build/scenariooDocumentation artifacts || true

    - store_artifacts:
        path: artifacts
        destination: /

    - run:
        name: Build Result Summary
        command: |
          echo -e "Build Result Summary:\n"
          cat ./artifacts/build-result-summary.txt
        when: always
